from .db import (
    get_pool,
    init_db,
    get_user,
    ensure_user,
    is_registered,
    save_registration,
    reset_registration,
    delete_user,
    log_user_action,
    get_user_references,
    get_user_articles_with_refs,
    get_user_stats,
    get_user_articles,
    get_article_info,
    get_reference,
    get_active_references,
    get_reference_count,
    soft_delete_reference,
    get_marketplace_cache,
    save_marketplace_cache,
    save_article,
    save_reference,
    deduct_balance,
    create_task,
    get_pending_tasks,
    complete_task,
    fail_task,
    fail_stuck_tasks,
    # generation_jobs (Вариант C)
    create_generation_job,
    create_job_task,
    get_pending_job_tasks,
    complete_job_task,
    fail_job_task,
    get_job_status,
    get_job_info,
    get_job_results,
    complete_generation_job,
    fail_generation_job,
    fail_stuck_jobs,
    # video job tasks
    create_video_job_task,
    get_pending_video_job_tasks,
    fail_stuck_video_jobs,
    # media_files
    register_media_file,
    get_unexported_media_files,
    get_all_unexported_media_files,
    mark_pinterest_exported,
    save_watermarked_path,
    get_media_file_by_id,
    # pinterest_settings
    get_pinterest_settings,
    save_pinterest_settings,
)

__all__ = [
    "get_pool",
    "init_db",
    "get_user",
    "ensure_user",
    "is_registered",
    "save_registration",
    "reset_registration",
    "delete_user",
    "log_user_action",
    "get_user_references",
    "get_user_articles_with_refs",
    "get_user_stats",
    "get_user_articles",
    "get_article_info",
    "get_reference",
    "get_active_references",
    "get_reference_count",
    "soft_delete_reference",
    "get_marketplace_cache",
    "save_marketplace_cache",
    "save_article",
    "save_reference",
    "deduct_balance",
    "create_task",
    "get_pending_tasks",
    "complete_task",
    "fail_task",
    "fail_stuck_tasks",
    # generation_jobs (Вариант C)
    "create_generation_job",
    "create_job_task",
    "get_pending_job_tasks",
    "complete_job_task",
    "fail_job_task",
    "get_job_status",
    "get_job_info",
    "get_job_results",
    "complete_generation_job",
    "fail_generation_job",
    "fail_stuck_jobs",
    # video job tasks
    "create_video_job_task",
    "get_pending_video_job_tasks",
    "fail_stuck_video_jobs",
    # media_files
    "register_media_file",
    "get_unexported_media_files",
    "get_all_unexported_media_files",
    "mark_pinterest_exported",
    "save_watermarked_path",
    "get_media_file_by_id",
    # pinterest_settings
    "get_pinterest_settings",
    "save_pinterest_settings",
]
